<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
    <line>
      <![CDATA[----Browser Session Started----]]>
    </line>
    <line>
      <![CDATA[=====Browser Session End=====]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="32793" started-at="2020-09-03T15:29:09Z" finished-at="2020-09-03T15:29:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32793" started-at="2020-09-03T15:29:09Z" finished-at="2020-09-03T15:29:41Z">
      <class name="ParaBank.TestCases.LoginValidationTest">
        <test-method status="PASS" signature="setupApplication()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="setupApplication" is-config="true" duration-ms="14965" started-at="2020-09-03T15:29:09Z" finished-at="2020-09-03T15:29:24Z">
          <reporter-output>
            <line>
              <![CDATA[----Browser Session Started----]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupApplication -->
        <test-method status="PASS" signature="BlankUserNamePassword()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="BlankUserNamePassword" duration-ms="4984" started-at="2020-09-03T15:29:24Z" finished-at="2020-09-03T15:29:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BlankUserNamePassword -->
        <test-method status="PASS" signature="InvalidUserNamePassword()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="InvalidUserNamePassword" duration-ms="3003" started-at="2020-09-03T15:29:29Z" finished-at="2020-09-03T15:29:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidUserNamePassword -->
        <test-method status="PASS" signature="OnlyPassword()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="OnlyPassword" duration-ms="2856" started-at="2020-09-03T15:29:32Z" finished-at="2020-09-03T15:29:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OnlyPassword -->
        <test-method status="PASS" signature="OnlyUsername()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="OnlyUsername" duration-ms="3181" started-at="2020-09-03T15:29:34Z" finished-at="2020-09-03T15:29:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OnlyUsername -->
        <test-method status="FAIL" signature="ValidUserNamePassword()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="ValidUserNamePassword" duration-ms="2691" started-at="2020-09-03T15:29:38Z" finished-at="2020-09-03T15:29:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ParaBank | Accounts Overview] but found [ParaBank | Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ParaBank | Accounts Overview] but found [ParaBank | Error]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at ParaBank.TestCases.LoginValidationTest.ValidUserNamePassword(LoginValidationTest.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidUserNamePassword -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:ParaBank.TestCases.LoginValidationTest@3f49dace]" name="closeApplication" is-config="true" duration-ms="1082" started-at="2020-09-03T15:29:40Z" finished-at="2020-09-03T15:29:41Z">
          <reporter-output>
            <line>
              <![CDATA[=====Browser Session End=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- ParaBank.TestCases.LoginValidationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
